name: Build and release SDK 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - release

jobs:
  build-and-release:
    runs-on: ubuntu-18.04
    steps:
      # Get the code into the container
      - name: Checkout
        uses: actions/checkout@v2
      # Create a new release
      - name: Semantic version bump
        uses: rimonhanna/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
      - name: Create tag for release
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            base_test.go
            base_util.go
            base.go
            client.go
            deta.go
            go.mod
            LICENSE
            README.md
          fail_on_unmatched_files: true
          prerelease: false
          name: Latest
          tag_name: latest
          draft: false
          body: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: deta/deta-go
